; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	C:\Users\polyr\Development\cpp\4k\i4k_OGL\src\intro.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?projectionmatrix@@3QBMB DD 03f800000r		; 1	; projectionmatrix
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03fa00000r			; 1.25
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800054r			; -1.00001
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bc23d740r			; -0.0100001
	DD	000000000r			; 0
?cubeVerts@@3QBMB DD 03f800000r			; 1	; cubeVerts
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
?cubeIndices@@3QBHB DD 00H				; cubeIndices
	DD	01H
	DD	02H
	DD	03H
	DD	04H
	DD	05H
	DD	06H
	DD	07H
	DD	08H
	DD	09H
	DD	0aH
	DD	0bH
	DD	0cH
	DD	0dH
	DD	0eH
	DD	0fH
	DD	010H
	DD	011H
	DD	012H
	DD	013H
	DD	014H
	DD	015H
	DD	016H
	DD	017H
CONST	ENDS
PUBLIC	?intro_init@@YGHXZ				; intro_init
PUBLIC	?intro_do@@YGXJ@Z				; intro_do
PUBLIC	__real@00000000
PUBLIC	__real@0000000000000000
PUBLIC	__real@3a83126f
PUBLIC	__real@3f1a0000
PUBLIC	__real@3ff0000000000000
PUBLIC	__real@40400000
EXTRN	__imp__glClear@4:PROC
EXTRN	__imp__glClearColor@16:PROC
EXTRN	__imp__glDisable@4:PROC
EXTRN	__imp__glDisableClientState@4:PROC
EXTRN	__imp__glDrawElements@16:PROC
EXTRN	__imp__glEnable@4:PROC
EXTRN	__imp__glEnableClientState@4:PROC
EXTRN	__imp__glLoadIdentity@0:PROC
EXTRN	__imp__glLoadMatrixf@4:PROC
EXTRN	__imp__glMatrixMode@4:PROC
EXTRN	__imp__glNormalPointer@12:PROC
EXTRN	__imp__glVertexPointer@16:PROC
EXTRN	_gluLookAt@72:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@40400000
CONST	SEGMENT
__real@40400000 DD 040400000r			; 3
CONST	ENDS
;	COMDAT __real@3ff0000000000000
CONST	SEGMENT
__real@3ff0000000000000 DQ 03ff0000000000000r	; 1
CONST	ENDS
;	COMDAT __real@3f1a0000
CONST	SEGMENT
__real@3f1a0000 DD 03f1a0000r			; 0.601563
CONST	ENDS
;	COMDAT __real@3a83126f
CONST	SEGMENT
__real@3a83126f DD 03a83126fr			; 0.001
CONST	ENDS
;	COMDAT __real@0000000000000000
CONST	SEGMENT
__real@0000000000000000 DQ 00000000000000000r	; 0
CONST	ENDS
;	COMDAT __real@00000000
CONST	SEGMENT
__real@00000000 DD 000000000r			; 0
CONST	ENDS
; Function compile flags: /Ogspy
; File c:\users\polyr\development\cpp\4k\i4k_ogl\src\intro.cpp
;	COMDAT ?intro_do@@YGXJ@Z
_TEXT	SEGMENT
_pos$$sroa$149$1$ = -8					; size = 4
_pos$$sroa$145$1$ = -4					; size = 4
_pos$$sroa$141$1$ = 8					; size = 4
_itime$ = 8						; size = 4
?intro_do@@YGXJ@Z PROC					; intro_do, COMDAT

; 77   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	push	ecx

; 78   :     const float ftime = 0.001f*(float)itime;

	fild	DWORD PTR _itime$[ebp]
	push	ebx
	push	esi

; 79   : 
; 80   :     // animate
; 81   :     float pos[3] = { 3.0f*cosf(ftime*p1d00), 
; 82   :                      3.0f*cosf(ftime*p0d60), 
; 83   :                      3.0f*sinf(ftime*p1d00) };
; 84   :     float tar[3] = { 0.0f, 0.0f, 0.0f };
; 85   : 
; 86   :     // render
; 87   : 	glEnable( GL_DEPTH_TEST );

	mov	esi, DWORD PTR __imp__glEnable@4
	push	edi
	fmul	DWORD PTR __real@3a83126f
	push	2929					; 00000b71H
	fld	ST(0)
	fcos
	fld	DWORD PTR __real@40400000
	fmul	ST(1), ST(0)
	fxch	ST(1)
	fstp	DWORD PTR _pos$$sroa$149$1$[ebp]
	fld	ST(1)
	fmul	DWORD PTR __real@3f1a0000
	fcos
	fmul	ST(0), ST(1)
	fstp	DWORD PTR _pos$$sroa$145$1$[ebp]
	fxch	ST(1)
	fsin
	fmulp	ST(1), ST(0)
	fstp	DWORD PTR _pos$$sroa$141$1$[ebp]
	call	esi

; 88   :     glEnable( GL_CULL_FACE );

	push	2884					; 00000b44H
	call	esi

; 89   : 	glDisable( GL_BLEND );

	push	3042					; 00000be2H
	call	DWORD PTR __imp__glDisable@4

; 90   :     glEnable( GL_LIGHTING );

	push	2896					; 00000b50H
	call	esi

; 91   :     glEnable( GL_LIGHT0 );

	push	16384					; 00004000H
	call	esi

; 92   :     glEnable( GL_NORMALIZE );

	push	2977					; 00000ba1H
	call	esi

; 93   : 
; 94   :     glClearColor( 0.0f, 0.0f, 0.0f, 0.0f );

	fldz
	sub	esp, 16					; 00000010H
	fst	DWORD PTR [esp+12]
	fst	DWORD PTR [esp+8]
	fst	DWORD PTR [esp+4]
	fstp	DWORD PTR [esp]
	call	DWORD PTR __imp__glClearColor@16

; 95   : 	glClear( GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT );

	push	16640					; 00004100H
	call	DWORD PTR __imp__glClear@4

; 96   : 
; 97   :     glMatrixMode( GL_PROJECTION );

	mov	esi, DWORD PTR __imp__glMatrixMode@4
	push	5889					; 00001701H
	call	esi

; 98   : 	glLoadMatrixf( projectionmatrix );

	push	OFFSET ?projectionmatrix@@3QBMB
	call	DWORD PTR __imp__glLoadMatrixf@4

; 99   :     glMatrixMode( GL_MODELVIEW );

	push	5888					; 00001700H
	call	esi

; 100  :     glLoadIdentity();

	call	DWORD PTR __imp__glLoadIdentity@0

; 101  :     gluLookAt( pos[0], pos[1], pos[2], tar[0], tar[1], tar[2], 0.0f, 1.0f, 0.0f );

	fldz
	sub	esp, 72					; 00000048H
	fst	QWORD PTR [esp+64]
	fld1
	fstp	QWORD PTR [esp+56]
	fst	QWORD PTR [esp+48]
	fst	QWORD PTR [esp+40]
	fst	QWORD PTR [esp+32]
	fstp	QWORD PTR [esp+24]
	fld	DWORD PTR _pos$$sroa$141$1$[ebp]
	fstp	QWORD PTR [esp+16]
	fld	DWORD PTR _pos$$sroa$145$1$[ebp]
	fstp	QWORD PTR [esp+8]
	fld	DWORD PTR _pos$$sroa$149$1$[ebp]
	fstp	QWORD PTR [esp]
	call	_gluLookAt@72

; 102  : 
; 103  :     // draw cube
; 104  :     glEnableClientState( GL_VERTEX_ARRAY );

	mov	esi, DWORD PTR __imp__glEnableClientState@4
	mov	ebx, 32884				; 00008074H
	push	ebx
	call	esi

; 105  : 	glEnableClientState( GL_NORMAL_ARRAY );

	lea	edi, DWORD PTR [ebx+1]
	push	edi
	call	esi

; 106  :     glVertexPointer( 3, GL_FLOAT, 6*sizeof(float), cubeVerts+0);

	push	OFFSET ?cubeVerts@@3QBMB
	push	24					; 00000018H
	mov	esi, 5126				; 00001406H
	push	esi
	push	3
	call	DWORD PTR __imp__glVertexPointer@16

; 107  :     glNormalPointer(    GL_FLOAT, 6*sizeof(float), cubeVerts+3);

	push	OFFSET ?cubeVerts@@3QBMB+12
	push	24					; 00000018H
	push	esi
	call	DWORD PTR __imp__glNormalPointer@12

; 108  : 	glDrawElements( GL_QUADS, 6*4, GL_UNSIGNED_INT, cubeIndices );

	push	OFFSET ?cubeIndices@@3QBHB
	push	5125					; 00001405H
	push	24					; 00000018H
	push	7
	call	DWORD PTR __imp__glDrawElements@16

; 109  : 	glDisableClientState( GL_NORMAL_ARRAY );

	mov	esi, DWORD PTR __imp__glDisableClientState@4
	push	edi
	call	esi

; 110  :     glDisableClientState( GL_VERTEX_ARRAY );

	push	ebx
	call	esi
	pop	edi
	pop	esi
	pop	ebx

; 111  : }

	mov	esp, ebp
	pop	ebp
	ret	4
?intro_do@@YGXJ@Z ENDP					; intro_do
_TEXT	ENDS
; Function compile flags: /Ogspy
; File c:\users\polyr\development\cpp\4k\i4k_ogl\src\intro.cpp
;	COMDAT ?intro_init@@YGHXZ
_TEXT	SEGMENT
?intro_init@@YGHXZ PROC					; intro_init, COMDAT

; 71   : 	return 1;

	xor	eax, eax
	inc	eax

; 72   : }

	ret	0
?intro_init@@YGHXZ ENDP					; intro_init
_TEXT	ENDS
; Function compile flags: /Ogspy
; File c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\math.h
;	COMDAT _sinf
_TEXT	SEGMENT
__X$ = 8						; size = 4
_sinf	PROC						; COMDAT

; 736  :         return (float)sin(_X);

	fld	DWORD PTR __X$[esp-4]
	fsin

; 737  :     }

	ret	0
_sinf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogspy
; File c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\math.h
;	COMDAT _cosf
_TEXT	SEGMENT
__X$ = 8						; size = 4
_cosf	PROC						; COMDAT

; 635  :         return (float)cos(_X);

	fld	DWORD PTR __X$[esp-4]
	fcos

; 636  :     }

	ret	0
_cosf	ENDP
_TEXT	ENDS
END
