; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	C:\Users\polyr\Development\cpp\4k\i4k_OGLShader\src\main_win_rel.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__fltused
_BSS	SEGMENT
__fltused DD	01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
?screenSettings@@3U_devicemodeA@@A DB 00H		; screenSettings
	ORG $+31
	DW	00H
	DW	00H
	DW	09cH
	DW	00H
	DD	01c0000H
	DW	00H
	ORG $+14
	DW	00H
	DW	00H
	DW	00H
	DW	00H
	DW	00H
	DB	00H
	ORG $+31
	DW	00H
	DD	020H
	DD	0780H
	DD	0438H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
_DATA	ENDS
CONST	SEGMENT
?wavHeader@@3QBHB DD 046464952H				; wavHeader
	DD	08bf764H
	DD	045564157H
	DD	020746d66H
	DD	010H
	DD	020001H
	DD	0ac44H
	DD	02b110H
	DD	0100004H
	DD	061746164H
	DD	08bf740H
?pfd@@3UtagPIXELFORMATDESCRIPTOR@@B DW 028H		; pfd
	DW	01H
	DD	025H
	DB	00H
	DB	020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	08H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DB	020H
	DB	00H
	DB	00H
	DB	00H
	DB	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?entrypoint@@YGXXZ				; entrypoint
EXTRN	__imp__ExitProcess@4:PROC
EXTRN	__imp__ChoosePixelFormat@8:PROC
EXTRN	__imp__SetPixelFormat@12:PROC
EXTRN	__imp__wglCreateContext@4:PROC
EXTRN	__imp__wglMakeCurrent@8:PROC
EXTRN	__imp__wglSwapLayerBuffers@8:PROC
EXTRN	__imp__CreateWindowExA@48:PROC
EXTRN	__imp__GetAsyncKeyState@4:PROC
EXTRN	__imp__GetDC@4:PROC
EXTRN	__imp__ShowCursor@4:PROC
EXTRN	__imp__ChangeDisplaySettingsA@8:PROC
EXTRN	__imp__sndPlaySoundA@8:PROC
EXTRN	__imp__timeGetTime@0:PROC
EXTRN	?intro_init@@YGHXZ:PROC				; intro_init
EXTRN	?intro_do@@YGXJ@Z:PROC				; intro_do
EXTRN	?mzk_init@@YGXPAF@Z:PROC			; mzk_init
_BSS	SEGMENT
?myMuzik@@3PAFA DW 08bf756H DUP (?)			; myMuzik
_BSS	ENDS
; Function compile flags: /Ogspy
; File c:\users\polyr\development\cpp\4k\i4k_oglshader\src\main_win_rel.cpp
;	COMDAT ?entrypoint@@YGXXZ
_TEXT	SEGMENT
?entrypoint@@YGXXZ PROC					; entrypoint, COMDAT

; 60   :     // full screen
; 61   :     if( ChangeDisplaySettings(&screenSettings,CDS_FULLSCREEN)!=DISP_CHANGE_SUCCESSFUL) return;

	push	4
	push	OFFSET ?screenSettings@@3U_devicemodeA@@A
	call	DWORD PTR __imp__ChangeDisplaySettingsA@8
	test	eax, eax
	jne	$LN1@entrypoint

; 62   :     ShowCursor( 0 );

	push	ebx
	xor	ebx, ebx
	push	ebx
	call	DWORD PTR __imp__ShowCursor@4

; 63   :     // create window
; 64   :     //HWND hWnd = CreateWindow( "static",0,WS_POPUP|WS_VISIBLE,0,0,XRES,YRES,0,0,0,0);
; 65   :     HWND hWnd = CreateWindow( (LPCSTR)0xC018,0,WS_POPUP|WS_VISIBLE,0,0,XRES,YRES,0,0,0,0);

	push	ebx
	push	ebx
	push	ebx
	push	ebx
	push	1080					; 00000438H
	push	1920					; 00000780H
	push	ebx
	push	ebx
	push	-1879048192				; 90000000H
	push	ebx
	push	49176					; 0000c018H
	push	ebx
	call	DWORD PTR __imp__CreateWindowExA@48

; 66   :     if( !hWnd ) return;

	test	eax, eax
	je	$LN14@entrypoint

; 67   :     HDC hDC = GetDC(hWnd);

	push	eax
	call	DWORD PTR __imp__GetDC@4
	mov	ebx, eax

; 68   :     // initalize opengl
; 69   :     if( !SetPixelFormat(hDC,ChoosePixelFormat(hDC,&pfd),&pfd) ) return;

	mov	eax, OFFSET ?pfd@@3UtagPIXELFORMATDESCRIPTOR@@B
	push	eax
	push	eax
	push	ebx
	call	DWORD PTR __imp__ChoosePixelFormat@8
	push	eax
	push	ebx
	call	DWORD PTR __imp__SetPixelFormat@12
	test	eax, eax
	je	$LN14@entrypoint

; 70   :     wglMakeCurrent(hDC,wglCreateContext(hDC));

	push	ebx
	call	DWORD PTR __imp__wglCreateContext@4
	push	eax
	push	ebx
	call	DWORD PTR __imp__wglMakeCurrent@8

; 71   : 
; 72   :     // init intro
; 73   :     if( !intro_init() ) return;

	call	?intro_init@@YGHXZ			; intro_init
	test	eax, eax
	je	SHORT $LN14@entrypoint

; 74   : 
; 75   :     // init mzk
; 76   :     mzk_init( myMuzik+22 );

	push	ebp
	push	esi
	push	edi
	push	OFFSET ?myMuzik@@3PAFA+44
	call	?mzk_init@@YGXPAF@Z			; mzk_init

; 77   :     memcpy( myMuzik, wavHeader, 44 );

	push	11					; 0000000bH
	pop	ecx

; 78   :     // play mzk
; 79   :     sndPlaySound( (const char*)&myMuzik, SND_ASYNC|SND_MEMORY );

	push	5
	mov	esi, OFFSET ?wavHeader@@3QBHB
	mov	edi, OFFSET ?myMuzik@@3PAFA
	rep movsd
	push	OFFSET ?myMuzik@@3PAFA
	call	DWORD PTR __imp__sndPlaySoundA@8

; 80   : 
; 81   :     // play intro
; 82   :     long t;
; 83   :     long to = timeGetTime();

	mov	edi, DWORD PTR __imp__timeGetTime@0
	call	edi
	mov	ebp, eax
$LL4@entrypoint:

; 84   :     do 
; 85   :     {
; 86   :         t = timeGetTime() - to;

	call	edi
	mov	esi, eax
	sub	esi, ebp

; 87   :         intro_do( t );

	push	esi
	call	?intro_do@@YGXJ@Z			; intro_do

; 88   :         wglSwapLayerBuffers( hDC, WGL_SWAP_MAIN_PLANE ); //SwapBuffers( hDC );

	push	1
	push	ebx
	call	DWORD PTR __imp__wglSwapLayerBuffers@8

; 89   :     }while ( !GetAsyncKeyState(VK_ESCAPE) && t<(MZK_DURATION*1000) );

	push	27					; 0000001bH
	call	DWORD PTR __imp__GetAsyncKeyState@4
	test	ax, ax
	jne	SHORT $LN9@entrypoint
	cmp	esi, 104000				; 00019640H
	jl	SHORT $LL4@entrypoint
$LN9@entrypoint:

; 90   : 
; 91   :     #ifdef CLEANDESTROY
; 92   :     sndPlaySound(0,0);
; 93   :     ChangeDisplaySettings( 0, 0 );
; 94   :     ShowCursor(1);
; 95   :     #endif
; 96   : 
; 97   :     ExitProcess(0);

	push	0
	call	DWORD PTR __imp__ExitProcess@4
	pop	edi
	pop	esi
	pop	ebp
$LN17@entrypoint:
$LN14@entrypoint:
	pop	ebx
$LN1@entrypoint:

; 98   : }

	ret	0
$LN16@entrypoint:
?entrypoint@@YGXXZ ENDP					; entrypoint
_TEXT	ENDS
END
